# Username
[username]
format = "[$user](bold yellow)"
disabled = false
show_always = true

# Hostname
[hostname]
ssh_only = false
format = "[$ssh_symbol](bold blue)[@](bold)[$hostname](bold green)[:](bold) "
trim_at = ".companyname.com"
disabled = false

# Directory setttings
[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"
