# Set the default image
FROM registry.fedoraproject.org/fedora:latest

# Install default packages
RUN dnf -y install \
        dos2unix \
        git \
        git-lfs \
        glibc-common \
        tar \
        tzdata \
        sudo \
        ccache \
        cmake \
        ninja-build \
        spdlog \
        spdlog-devel \
        curl \
        gcc \
        g++ \
        gdb \
        python3-pip

# Install language servers
RUN pip install black python-lsp-server debugpy pynvim cmake-language-server && \
        dnf install clang-tools-extra

# Set environment variables
ENV PATH="/root/bin:${PATH}"


