#!/bin/bash

## Personal aliases
alias chrome="flatpak run com.brave.Browser"

alias fp='fzf --preview "bat -n --color=always {}"'
alias fn='nvim "${fp}"'
alias ls='lsd -Fl'
alias ll='lsd -Fl'
alias l='lsd -Fl -A'
