#!/bin/bash

## Personal aliases
alias chrome="flatpak run com.brave.Browser"

alias sudo='doas'
alias sudoedit='doas nvim'

alias fp='fzf --preview "bat -n --color=always {}"'
alias fn='nvim "${fp}"'
alias ls='lsd'
alias l='lsd -l -A'
