#!/bin/sh

### CONSERVATION MODE
_conservation-mode(){
    if [ "${#COMP_WORDS[@]}" != "2" ]; then
        return
    fi

    local cur=${COMP_WORDS[COMP_CWORD]}
    COMPREPLY=( $(compgen -W "on off" -- $cur))
}
complete -F _conservation-mode conservation-mode

### OTHERS
# bash parameter completion for the dotnet CLI

_dotnet_bash_complete()
{
  local word=${COMP_WORDS[COMP_CWORD]}

  local completions
  completions="$(dotnet complete --position "${COMP_POINT}" "${COMP_LINE}" 2>/dev/null)"
  if [ $? -ne 0 ]; then
    completions=""
  fi

  COMPREPLY=( $(compgen -W "$completions" -- "$word") )
}

complete -f -F _dotnet_bash_complete dotnet
