#!/bin/bash
###############################################################################
##### SYSTEM UPDATE                                                     #######
###############################################################################
update() {
    echo '-------------------------'
    echo '-------- UPDATE ---------'
    echo '-------------------------'
    sudo dnf update --refresh
    echo ''

    echo '-------------------------'
    echo '-------- FLATPAK --------'
    echo '-------------------------'
    flatpak update -y
    echo ''

    # Rust Update
    echo '-------------------------'
    echo '---------- RUST ---------'
    echo '-------------------------'
    rustup update
    echo ''
}

###############################################################################
####### BACKUP                                                           ######
###############################################################################
tar-pack() {
    filename=$(basename "$1")
    tar --zstd -cvf "$filename".tar.zst "$1"
}

tar-unpack() {
    tar --zstd -xvf "$1"
}

backup-files() {
    cd ~ || exit
    ## BRAVE
    tar-pack .config/BraveSoftware/
    tar-pack .dotfiles
    tar-pack Private
    tar-pack Work
    tar-pack Projects
    tar-pack .ssh
    tar-pack .gitconfig

    udisksctl mount --block-device /dev/sda1
    mv -f ~/*.tar.zst "/run/media/$USER/Backup/Linux/"
}
