#!/bin/sh
###############################################################################
##### SYSTEM UPDATE                                                     #######
###############################################################################
function update(){
    echo '-------------------------'
    echo '--------- DNF -----------'
    echo '-------------------------'
    sudo dnf update --refresh
    #     echo '-------------------------'
    #     echo '--------- APT -----------'
    #     echo '-------------------------'
    #     sudo apt update && sudo apt upgrade
    echo ''

    echo '-------------------------'
    echo '------- Flatpak ---------'
    echo '-------------------------'
    flatpak update -y
}

###############################################################################
##### GRUB UPDATE                                                       #######
###############################################################################
function grub-update(){
    echo "Update grub"
    sudo grub2-mkconfig -o /etc/grub2.cfg
    sudo grub2-mkconfig -o /etc/grub2-efi.cfg
}

###############################################################################
##### UPDATE MAJOR TOOLS                                                #######
###############################################################################
function update-tools(){
    __update-rust
    __update-starship
    __update-emscripten
    __update-espIdf
    __update-poetry
}

function __update-rust(){
    # Rust Update
    echo '-------------------------'
    echo '-------- RUST -----------'
    echo '-------------------------'
    rustup update
    echo ''
}

function __update-starship(){
    # Rust Update
    echo '-------------------------'
    echo '------ STARSHIP ---------'
    echo '-------------------------'
    curl -sS https://starship.rs/install.sh | sh -s -- --bin-dir ~/.local/bin -y
    echo ''
}

function __update-emscripten(){
    if [[ "$XDG_SESSION_DESKTOP" == "KDE" ]];
    then
        # # Emscripten update
        echo '-------------------------'
        echo '----- EMSCRIPTEN --------'
        echo '-------------------------'
        cd ~/Software/emsdk
        pull=$(git pull)
        if [[ $pull != "Already up to date." ]];
        then
            ~/Software/emsdk/emsdk install latest
            ~/Software/emsdk/emsdk activate latest
        else
            echo $pull
        fi
        cd ~
        echo ''
    fi
}

function __update-espIdf(){
    # Esp-Idf
    echo '-------------------------'
    echo '------- ESP-IDF ---------'
    echo '-------------------------'
    cd ~/Software/esp-idf
    pull=$(git pull)
    if [[ $pull != "Already up to date." ]];
    then
        git pull --recurse-submodules
        sh ~/Software/esp-idf/install.sh
    else
        echo $pull
    fi
    cd ~
    echo ''
}

function __update-poetry(){
    # Poetry
    echo '-------------------------'
    echo '------- POETRY  ---------'
    echo '-------------------------'
    poetry self update
    echo ''
}