#!/bin/bash

export FZF_DEFAULT_OPTS="--border"

# fe [FUZZY PATTERN] - Open the selected file with the default editor
#   - Bypass fuzzy finder if there's only one match (--select-1)
#   - Exit if there's no match (--exit-0)
fe() {
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-nvim} "${files[@]}"
}

# using ripgrep combined with preview
# find-in-file - usage: fif <searchTerm>
fif() {
  if [ ! "$#" -gt 0 ]; then echo "Need a string to search for!"; return 1; fi
  rg --files-with-matches --no-messages "$1" | fzf --preview "highlight -O ansi -l {} 2> /dev/null | rg --colors 'match:bg:yellow' --ignore-case --pretty --context 10 '$1' || rg --ignore-case --pretty --context 10 '$1' {}"
}

# fshow - git commit browser
fshow() {
git log --graph --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr"  | \
 fzf --ansi --no-sort --reverse --tiebreak=index --preview \
 'f() { set -- $(echo -- "$@" | grep -o "[a-f0-9]\{7\}"); [ $# -eq 0 ] || git show --color=always $1 ; }; f {}' \
 --bind "alt-j:preview-down,alt-k:preview-up,ctrl-m:execute:
              (grep -o '[a-f0-9]\{7\}' | head -1 |
              xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
              {}
FZF-EOF" --preview-window=right:60%
}

# Select a podman container to start and attach to
pa() {
  local cid
  cid=$(podman ps -a | sed 1d | fzf -1 -q "$1" | awk '{print $1}')
  [ -n "$cid" ] && podman start "$cid" && podman attach "$cid"
}

# Select a podman container to start and run interactively
pit() {
  local cid
  cid=$(podman images | sed 1d | fzf -1 -q "$1" | awk '{print $1}')
  [ -n "$cid" ] && podman run -it "$cid" /bin/bash
}

# Select a running podman container to stop
ps() {
  local cid
  cid=$(podman ps | sed 1d | fzf -q "$1" | awk '{print $1}')
  [ -n "$cid" ] && podman stop "$cid"
}

# Select a podman container to remove
prm() {
  podman ps -a | sed 1d | fzf -q "$1" --no-sort -m --tac | awk '{ print $1 }' | xargs -r podman rm -f
}

# Select a podman image or images to remove
prmi() {
  podman images | sed 1d | fzf -q "$1" --no-sort -m --tac | awk '{ print $3 }' | xargs -r podman rmi -f
  podman image prune -f
}
