#!/usr/bin/env bash

###############################################
# FZF Commands
###############################################
# Files (CTRL-T, default)
export FZF_DEFAULT_COMMAND="rg --files --no-ignore-vcs \
  --glob '!*/{.git,node_modules,.cov-idir,jacoco-files}/**'"

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Directories (ALT-C)
export FZF_ALT_C_COMMAND="fd --type d --no-ignore-vcs --strip-cwd-prefix \
  --exclude node_modules \
  --exclude .git \
  --exclude .cov-idir \
  --exclude jacoco-files"

###############################################
# FZF UI Defaults
###############################################
export FZF_DEFAULT_OPTS="\
--highlight-line \
--info=inline-right \
--layout=reverse \
--border=none"

# # # Catppuccin Macchiato Theme https://github.com/catppuccin/fzf/blob/main/themes/catppuccin-fzf-macchiato.sh
# export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} \
# --color=bg+:#363A4F,bg:#24273A,spinner:#F4DBD6,hl:#ED8796 \
# --color=fg:#CAD3F5,header:#ED8796,info:#C6A0F6,pointer:#F4DBD6 \
# --color=marker:#B7BDF8,fg+:#CAD3F5,prompt:#C6A0F6,hl+:#ED8796 \
# --color=selected-bg:#494D64 \
# --color=border:#6E738D,label:#CAD3F5"

# Catppuccin Macchiato Theme https://github.com/catppuccin/fzf/blob/main/themes/catppuccin-fzf-mocha.sh
# export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} \
# --color=bg+:#313244,bg:#1E1E2E,spinner:#F5E0DC,hl:#F38BA8 \
# --color=fg:#CDD6F4,header:#F38BA8,info:#CBA6F7,pointer:#F5E0DC \
# --color=marker:#B4BEFE,fg+:#CDD6F4,prompt:#CBA6F7,hl+:#F38BA8 \
# --color=selected-bg:#45475A \
# --color=border:#6C7086,label:#CDD6F4"

# CTRL-T (file picker)
export FZF_CTRL_T_OPTS="
  --preview='cat {}' \
  --bind shift-up:preview-page-up,shift-down:preview-page-down
"
###############################################
# fe — Open selected files in your $EDITOR
###############################################
fe() {
  local selection
  IFS=$'\n' read -d '' -r -a selection < <(
    fzf-tmux --query="$1" --multi --select-1 --exit-0 && printf '\0'
  )

  if [ ${#selection[@]} -gt 0 ]; then
    "${EDITOR:-nvim}" "${selection[@]}"
  fi
}

###############################################
# fif — Search text inside files (ripgrep + cat)
###############################################
fif() {
  if [ $# -lt 1 ]; then
    echo "Usage: fif <pattern>"
    return 1
  fi

  rg --files-with-matches --no-messages "$1" \
    | fzf --ansi --preview "
        cat {} \
        | rg --colors 'match:bg:yellow' --ignore-case --pretty --context 10 '$1'
      "
}

###############################################
# fkill — Fuzzy kill
###############################################
fkill() {
  local pid
  pid=$(ps -eo pid,user,%cpu,%mem,command --sort=-%cpu \
        | fzf --header-lines=1 --reverse --no-sort \
        | awk '{print $1}')

  if [[ -n "$pid" ]]; then
    printf "%s\n" "$pid" | xargs kill -"${1:-9}"
  fi
}
