#!/bin/bash

## Personal aliases
alias chrome="flatpak run com.brave.Browser"
alias wezterm="flatpak run org.wezfurlong.wezterm"
alias rm='rm -i'

## Environment Variables
export LIBVIRT_DEFAULT_URI="qemu:///system"
export DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock

# Custom scripts autocomplete
export PATH="$PATH":"$HOME"/.scripts
source "$HOME/.scripts/commands"

# Set Editor to NVIM
export EDITOR="$HOME/.local/bin/nvim"
export VISUAL="$HOME/.local/bin/nvim"

# add Local to PATH
export PATH="$PATH":"$HOME"/.local/bin

# Rust
source "$HOME/.cargo/env"

# Android
export ANDROID_HOME="$HOME"/Software/Android/Sdk
export PATH="$PATH":"$ANDROID_HOME"/platform-tools

# Flutter
export PATH="$PATH":"$HOME"/Software/flutter/bin
export CHROME_EXECUTABLE="flatpak run com.brave.Browser"

# Go
export PATH="$PATH":"$HOME"/Software/go/bin
export GOPATH="$HOME"/Software/go
alias bazel="bazelisk"

# Espressif
alias getIdf=". $HOME/Software/esp-idf/export.sh"

# Emscripten
alias getEmsdk="source $HOME/Software/emsdk/emsdk_env.sh"

# JAVA_HOME
JAVA_HOME="$(dirname "$(dirname "$(realpath "$(which javac)")")")"
export JAVA_HOME
