#!/bin/sh

## Personal aliases
alias balanced='powerprofilesctl set balanced'
alias power-saver='powerprofilesctl set power-saver'
alias chrome='brave-browser-stable'
alias reboot='systemctl reboot'
alias shutdown='systemctl poweroff'
alias vim='nvim'
alias wezterm='flatpak run org.wezfurlong.wezterm'

source ~/.scripts/wezterm.sh

## Environment Variables
export LIBVIRT_DEFAULT_URI='qemu:///system'

# Custom scripts autocomplete
export PATH=$PATH:$HOME/.scripts
source "$HOME/.scripts/commands"
# source "$HOME/.scripts/bash_completions"
# source "$HOME/.scripts/zsh_completions"

# Set Editor to NVIM
export EDITOR='nvim'
export VISUAL='nvim'

# add Local to PATH
export PATH=$PATH:$HOME/.local/bin

# Rust
source "$HOME/.cargo/env"

# Android
export ANDROID_HOME=$HOME/Software/Android/Sdk
# alias fastboot='sudo $ANDROID_HOME/platform-tools/fastboot'
# alias adb='sudo $ANDROID_HOME/platform-tools/adb'

# Flutter
export PATH=$PATH:$HOME/Software/flutter/bin
export CHROME_EXECUTABLE=brave-browser-stable

# Go
export PATH=$PATH:/usr/local/go/bin

# Espressif
alias getIdf='. $HOME/Software/esp-idf/export.sh'

# Emscripten
alias getEmsdk='source $HOME/Software/emsdk/emsdk_env.sh'

# JAVA_HOME
# export JAVA_HOME='/usr/lib/jvm/java-17-openjdk-17.0.3.0.7-1.fc36.x86_64/bin/java'
# export JAVA_HOME='/usr/lib/jvm/java-11-openjdk-11.0.15.0.10-1.fc36.x86_64/bin/java'
