#!/bin/bash

# I install all my software in a folder ~/Software
# Find all bin directories in ~/Software and append them to PATH
SOFTWARE_DIR="$HOME/Software"
path_add() {
    case ":${PATH}:" in
    *:"$1":*) ;;
    *)
        if [ "$2" = "after" ]; then
            PATH=$PATH:$1
        else
            PATH=$1:$PATH
        fi
        ;;
    esac
}

for bin_dir in $(find "$SOFTWARE_DIR" -type d -name bin); do
    path_add $bin_dir
done
path_add "/sbin"
path_add "/usr/sbin"
path_add "/usr/local/sbin"
path_add "$HOME/.local/bin"
path_add "$HOME/.scripts"

## Personal aliases
alias chrome="flatpak run com.brave.Browser"
alias ls='eza'
alias l='ls -l'
alias la='ls -la'
alias fp='fzf --preview "bat -n --color=always {}"'
alias fn='nvim "${fp}"'

alias docker='podman'
alias docker-compose='podman-compose'

## EDITOR
export EDITOR=nvim
export VISUAL=nvim

## Environment Variables
export LIBVIRT_DEFAULT_URI="qemu:///system"
export DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock

# Custom scripts autocomplete
source "$HOME/.scripts/commands"
source "$HOME/.scripts/fzf_commands"

# Rust
source "$HOME/.cargo/env"

# Android
export ANDROID_HOME="$HOME"/Software/Android/Sdk
path_add "$ANDROID_HOME/platform-tools"

# Flutter
export CHROME_EXECUTABLE="flatpak run com.brave.Browser"

# Go
export GOPATH="$SOFTWARE_DIR/go"
alias bazel="bazelisk"

# JAVA_HOME
JAVA_HOME="$(dirname "$(dirname "$(realpath "$(which javac)")")")"
export JAVA_HOME
