#!/bin/bash

update() {
  echo '-------------------------'
  echo '-------- UPDATE ---------'
  echo '-------------------------'
  doas dnf update --refresh
  echo ''

  echo '-------------------------'
  echo '-------- FLATPAK --------'
  echo '-------------------------'
  flatpak update --assumeyes
  echo ''

  __update-dev-tools
  __update-neovim
  __update-kitty
}

__update-dev-tools() {
  echo '-------------------------'
  echo '------ DEV TOOLING ------'
  echo '-------------------------'
  rustup update
  cargo install-update -a

  uv self update
  uv tool upgrade --all
  echo ''
}

__update-neovim() {
  echo '-------------------------'
  echo '--------- NEOVIM --------'
  echo '-------------------------'
  local_nvim_version=$(nvim --version | head -n1 | sed 's/^NVIM //')
  latest_nvim_version=$(curl -L https://api.github.com/repos/neovim/neovim/releases/latest 2>/dev/null | jq --raw-output '.tag_name')
  if [[ "$local_nvim_version" != "$latest_nvim_version" ]]; then
    doas curl --location https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage --output /usr/local/bin/nvim
    doas chmod 755 /usr/local/bin/nvim
  else
    echo 'Already up to date'
  fi
  echo ''
}

__update-kitty() {
  echo '-------------------------'
  echo '---------- KITTY --------'
  echo '-------------------------'
  local_kitty_version=$(kitty --version | awk '{print $2}')
  latest_kitty_version=$(curl -sL https://api.github.com/repos/kovidgoyal/kitty/releases/latest | jq -r '.tag_name' | sed 's/^v//')
  if [[ "$local_kitty_version" != "$latest_kitty_version" ]]; then
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n
  else
    echo 'Already up to date'
  fi
  echo ''
}
