#!/bin/bash

update() {
  echo '-------------------------'
  echo '-------- UPDATE ---------'
  echo '-------------------------'
  sudo dnf update --refresh
  echo ''

  echo '-------------------------'
  echo '-------- FLATPAK --------'
  echo '-------------------------'
  flatpak update -y
  echo ''

  __update-dev-tools
}

__update-dev-tools() {
  echo '-------------------------'
  echo '------ DEV TOOLING ------'
  echo '-------------------------'
  rustup update
  uv self update
  uv tool upgrade --all
  echo ''
}
