#!/bin/bash

print_help() {
    echo "Usage: $0 -u <url> -v <version> [-t]"
    echo ""
    echo "Parameters:"
    echo "  -u, --url            The URL of the VSCode marketplace extension site (e.g. https://marketplace.visualstudio.com/items?itemName=ms-python.python)"
    echo "  -v, --version        The version of the package that you want"
    echo "  -t, --target_platform  (Optional) Trigger the target platform selection menu."
    echo ""
    echo "The currently available platforms are:"
    echo "1: win32-x64"
    echo "2: win32-arm64"
    echo "3: linux-x64"
    echo "4: linux-arm64"
    echo "5: linux-armhf"
    echo "6: alpine-x64"
    echo "7: alpine-arm64"
    echo "8: darwin-x64"
    echo "9: darwin-arm64"
    echo "10: web"
    exit 1
}

select_platform() {
    echo "Select a platform:"
    local platforms=("win32-x64" "win32-arm64" "linux-x64" "linux-arm64" "linux-armhf" "alpine-x64" "alpine-arm64" "darwin-x64" "darwin-arm64" "web")
    for i in "${!platforms[@]}"; do
        printf "%3d: %s\n" $((i + 1)) "${platforms[$i]}"
    done

    read -p "Choose an option [1-10]: " platform_choice

    if [[ $platform_choice -ge 1 && $platform_choice -le ${#platforms[@]} ]]; then
        echo "${platforms[$platform_choice-1]}"
    else
        echo "Invalid choice" >&2
        exit 2
    fi
}

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -u|--url)
            url="$2"
            shift
            ;;
        -v|--version)
            version="$2"
            shift
            ;;
        -t|--target_platform)
            target_platform_flag=1
            ;;
        -h|--help)
            print_help
            ;;
        *)
            echo "Unknown parameter passed: $1"
            print_help
            ;;
    esac
    shift
done

if [ -z "$url" ] || [ -z "$version" ]; then
    echo "URL and version are required parameters"
    print_help
fi

# Extract publisher and package name from the URL
publisher=$(echo "$url" | grep -oP '(?<=itemName=)[^.]*(?=\.)')
package=$(echo "$url" | grep -oP '(?<=\.)[^&]*$')

if [ -n "$target_platform_flag" ]; then
    target_platform=$(select_platform)
    final_url="https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${publisher}/vsextensions/${package}/${version}/vspackage?targetPlatform=${target_platform}"
else
    final_url="https://marketplace.visualstudio.com/_apis/public/gallery/publishers/${publisher}/vsextensions/${package}/${version}/vspackage"
fi

echo "Generated URL: $final_url"
